### ISSUE TITLE
Root Issue

### ISSUE THREAD

**Issue by krlee407** [snu-entrance/DJbamboo_wk#1]
목표
 - [DJbamboo](http://www.datamarket.kr/xe/board_pdzw77/29247)를 실사용이 가능하게끔 구현하기

방법
 - 플친 <-> 서버를 나눠서 구현해서, 서로 json(이나 통신하기 편한 형태)으로 정보를 주고 받는다.

1. 플친에서 텍스트(사연)을 입력받아 그대로 서버로 보내줌
2. 서버에서 받은 텍스트(사연)를 훈련된 모델에 인풋으로 넣고 아웃풋으로 _노래를 출력한 뒤, 플친으로 보낸다._
3. 플친은 이를 받아 _유저에게 출력해준다._

기획 요소

- [x] 모델에서 출력된 노래를 플친으로 보낼때, 텍스트로 노래 정보를 보내면, 카톡에선 어떻게 유저에게 그 노래를 전달할 것인가? 1. 텍스트로? 2. 노래로?
`텍스트로 보내서, 카톡에서 멜론으로 노래 재생시켜주기로 함, 안되면 그때 대안을 생각하기로`

할 일

- [ ] 플친 개발 (담당자 미정) #2 
- [ ] 웹서버 구현 (flask, python)  @toastls93 #3 
- [ ] 모델 튜닝 @krlee407 @dhchoi1457 #4

**Comment by krlee407** [comment]
데이터 수집 Issue!

- [ ] test에 쓸 대숲 데이터 구할 코드 작성 @toastls93, @krlee407 #5

eval은 나중에 생각하고

**Comment by krlee407** [comment]
- [ ] tobigs 공용서버 사용 가능 여부 알아보기 @dhchoi1457
- [ ] 맞춤법 검사기 API 서비스에 포함시킬 수 있는거 알아보기 @toastls93
